apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart11.fullname" . }}-podinfo
  labels:
  {{- include "chart11.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.podinfo.replicas }}
  selector:
    matchLabels:
      app: podinfo
    {{- include "chart11.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: podinfo
      {{- include "chart11.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/port: "9797"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: {{ quote .Values.podinfo.podinfod.env.podinfoUiColor }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.podinfo.podinfod.image.repository }}:{{ .Values.podinfo.podinfod.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.podinfo.podinfod.imagePullPolicy }}
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: podinfod
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        - containerPort: 9797
          name: http-metrics
          protocol: TCP
        - containerPort: 9999
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources: {{- toYaml .Values.podinfo.podinfod.resources | nindent 10 }}
      serviceAccountName: {{ include "chart11.fullname" . }}-