apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart11.fullname" . }}-
  labels:
  {{- include "chart11.labels" . | nindent 4 }}
spec:
  host: podinfo-demo.apps.fqywlnxx.eastus.aroapp.io
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo