apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart2.fullname" . }}-podinfo
  labels:
  {{- include "chart2.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo