apiVersion: v1
kind: Route
metadata:
  name: {{ include "chart1.fullname" . }}-
  labels:
  {{- include "chart1.labels" . | nindent 4 }}
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  spec:
    host: podinfo-demo.apps.fqywlnxx.eastus.aroapp.io
    port:
      targetPort: http
    to:
      kind: Service
      name: podinfo