apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart.fullname" . }}-podinfo
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  host: appdemo.apps.fqywlnxx.eastus.aroapp.io
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo-git-mychart-podinfo