apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart3.fullname" . }}-podinfo
  labels:
  {{- include "chart3.labels" . | nindent 4 }}
spec:
  host: podinfo-git-chart2-podinfo-openshift-gitops.apps.fqywlnxx.eastus.aroapp.io
  port:
    targetPort: http
  to:
    kind: Service
    name: podinfo-git-chart2-podinfo